name: 🐛 Bug Report
description: Report a bug or issue with the P&L Tool
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! The more details you provide, the faster we can help you.

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency Level
      description: How urgent is this bug?
      options:
        - Low - Minor inconvenience, workaround available
        - Medium - Affects functionality but not critical
        - High - Blocks important functionality
        - Critical - Breaks core functionality or prevents deployment
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Area
      description: Which part of the application is affected?
      options:
        - Calculations (P&L logic)
        - User Interface (forms, buttons, layout)
        - Data Persistence (saving/loading data)
        - Regional Features (US/Canada differences)
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened vs what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter values '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Mobile Chrome (Android)
        - Other
    validations:
      required: false

  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Tablet
        - Mobile Phone
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, error messages, etc.)
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true
        - label: I have included the urgency level and affected area
          required: true