name: ✨ Feature Request
description: Suggest a new feature or enhancement for the P&L Tool
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand what you need and why.

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve user experience
        - High - Important for business goals
        - Critical - Blocking important use cases
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Calculation Enhancement
        - User Interface Improvement
        - New Regional Support
        - Performance Optimization
        - Data Export/Import
        - Reporting/Analytics
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Who benefits from it?
      placeholder: "As a [user type], I need [capability] so that [benefit/outcome]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution or how you envision this feature working
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
    validations:
      required: false

  - type: textarea
    id: mockup
    attributes:
      label: Mockups/Examples
      description: If applicable, provide mockups, screenshots, or examples from other tools
    validations:
      required: false

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort (if known)
      description: If you have technical knowledge, estimate the complexity
      options:
        - Small - Few hours to 1 day
        - Medium - 2-5 days
        - Large - 1-2 weeks
        - Extra Large - 2+ weeks
        - Unknown
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Expected Impact
      description: What areas would this feature affect?
      options:
        - label: User Experience
        - label: Performance
        - label: Calculation Accuracy
        - label: Data Management
        - label: Accessibility
        - label: Mobile Experience
        - label: Backend/Infrastructure

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, requirements, or considerations?
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and features
          required: true
        - label: I have clearly described the problem and solution
          required: true
        - label: I have provided business justification
          required: true