name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Suggest a new feature or enhancement for the Liberty Tax P&L webapp.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        - What current limitation or pain point does this address?
        - What user need is not being met?
        - What workflow could be improved?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe in detail:
        - Where would this feature appear in the UI?
        - How would users interact with it?
        - What would be the expected behavior?
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the app would this feature affect?
      options:
        - Wizard (Welcome/Inputs/Review pages)
        - Dashboard/KPI display
        - Debug panel
        - Calculations/formulas
        - Data persistence/export
        - Mobile/responsive design
        - Performance/optimization
        - User experience/UI
        - Regional features (US/CA)
        - New functionality
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Primary User Type
      description: Who would primarily benefit from this feature?
      options:
        - Tax office owners/operators
        - Liberty Tax franchisees
        - Business analysts
        - Support agents
        - Developers/testers
        - All users
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Critical - Blocks key workflows
        - High - Significantly improves user experience
        - Medium - Nice to have improvement
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Specific scenarios where this feature would be used
      placeholder: |
        1. When a user needs to...
        2. During the process of...
        3. To help with...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How would we know this feature is working correctly?
      placeholder: |
        - [ ] Feature appears in correct location
        - [ ] User can perform expected actions
        - [ ] Data is handled correctly
        - [ ] Works on mobile devices
        - [ ] Integrates with existing features
        - etc.

  - type: checkboxes
    id: testing-considerations
    attributes:
      label: Testing Considerations
      description: What testing would this feature require?
      options:
        - label: Unit testing for calculations
        - label: Integration testing with existing features
        - label: Mobile/responsive testing
        - label: Cross-browser compatibility testing
        - label: Performance testing
        - label: Accessibility testing
        - label: User acceptance testing
        - label: Edge case testing

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
      placeholder: |
        - Other ways to solve the same problem
        - Existing workarounds
        - Similar features in other apps

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: |
        - Screenshots or mockups
        - Examples from other applications
        - User feedback or requests
        - Business requirements
