/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
  '/api/health': {
    /** Health check */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': {
              /** @example ok */
              status?: string;
            };
          };
        };
      };
    };
  };
  '/api/reports/summary': {
    /** Get P&L summary */
    get: {
      parameters: {
        query?: {
          region?: 'US' | 'CA';
          year?: number;
        };
      };
      responses: {
        /** @description Summary report */
        200: {
          content: {
            'application/json': {
              netIncome?: number;
              netMargin?: number;
              totalRevenue?: number;
            };
          };
        };
      };
    };
  };
};

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
