# Development Environment Setup Script
# Place this in your D:\Dev\ directory and run it to configure your development environment

Write-Host "🚀 Setting up Development Environment..." -ForegroundColor Green

# Define development paths
$DevPaths = @(
    'D:\Dev\nodejs',
    'D:\Dev\nvm',
    'D:\Dev\git\bin',
    'D:\Dev\tools',
    'D:\Dev\scripts'
)

# Current session PATH update
Write-Host "📝 Updating PATH for current session..." -ForegroundColor Yellow
foreach ($path in $DevPaths) {
    if (Test-Path $path) {
        $env:Path = $env:Path + ";$path"
        Write-Host "  ✅ Added: $path" -ForegroundColor Green
    } else {
        Write-Host "  ⚠️  Not found: $path" -ForegroundColor Yellow
    }
}

# Verify tools are available
Write-Host "`n🔍 Verifying development tools..." -ForegroundColor Yellow

try {
    $nodeVersion = node -v
    Write-Host "  ✅ Node.js: $nodeVersion" -ForegroundColor Green
} catch {
    Write-Host "  ❌ Node.js not found" -ForegroundColor Red
}

try {
    $npmVersion = npm -v
    Write-Host "  ✅ npm: $npmVersion" -ForegroundColor Green
} catch {
    Write-Host "  ❌ npm not found" -ForegroundColor Red
}

try {
    $gitVersion = git --version
    Write-Host "  ✅ Git: $gitVersion" -ForegroundColor Green
} catch {
    Write-Host "  ❌ Git not found" -ForegroundColor Red
}

# PowerShell Profile setup
Write-Host "`n📋 PowerShell Profile Configuration..." -ForegroundColor Yellow

$profileContent = @"
# Development Environment Auto-Setup
# Generated by setup-dev-environment.ps1

# Development tool paths
`$DevPaths = @(
    'D:\Dev\nodejs',
    'D:\Dev\nvm',
    'D:\Dev\git\bin',
    'D:\Dev\tools',
    'D:\Dev\scripts'
)

# Add development paths to PATH
foreach (`$path in `$DevPaths) {
    if ((Test-Path `$path) -and (`$env:Path -notlike "*`$path*")) {
        `$env:Path = `$env:Path + ";`$path"
    }
}

# Development aliases
Set-Alias -Name ll -Value Get-ChildItem
Set-Alias -Name grep -Value Select-String

# Quick navigation functions
function dev { Set-Location "D:\Dev" }
function projects { Set-Location "D:\Dev\projects" }
function tools { Set-Location "D:\Dev\tools" }

# Git shortcuts
function gs { git status }
function ga { git add . }
function gc { param([string]`$message) git commit -m `$message }
function gp { git push }
function gl { git log --oneline -10 }

# npm shortcuts
function ni { npm install }
function ns { npm start }
function nt { npm test }
function nb { npm run build }

# Quick project setup
function setup-project {
    param([string]`$name)
    if (`$name) {
        New-Item -ItemType Directory -Path "D:\Dev\projects\`$name" -Force
        Set-Location "D:\Dev\projects\`$name"
        Write-Host "📁 Created and navigated to: D:\Dev\projects\`$name" -ForegroundColor Green
    } else {
        Write-Host "Usage: setup-project <project-name>" -ForegroundColor Yellow
    }
}

Write-Host "✅ Development environment loaded!" -ForegroundColor Green
"@

if (!(Test-Path $PROFILE)) {
    New-Item -ItemType File -Path $PROFILE -Force | Out-Null
}

Set-Content -Path $PROFILE -Value $profileContent
Write-Host "  ✅ PowerShell profile updated: $PROFILE" -ForegroundColor Green

Write-Host "`n🎯 Setup Complete!" -ForegroundColor Green
Write-Host "Run '. `$PROFILE' to reload your profile, or restart PowerShell" -ForegroundColor Yellow
Write-Host "`nUseful commands:" -ForegroundColor Cyan
Write-Host "  dev          - Navigate to D:\Dev" -ForegroundColor White
Write-Host "  projects     - Navigate to D:\Dev\projects" -ForegroundColor White
Write-Host "  setup-project <name> - Create new project directory" -ForegroundColor White
Write-Host "  gs           - git status" -ForegroundColor White
Write-Host "  ga           - git add ." -ForegroundColor White
Write-Host "  gc 'message' - git commit -m 'message'" -ForegroundColor White
Write-Host "  ni           - npm install" -ForegroundColor White
Write-Host "  nt           - npm test" -ForegroundColor White
