name: Deploy to Staging (Debug Mode)

on:
  workflow_dispatch:
    inputs:
      debug_level:
        description: 'Debug level (basic/verbose/full)'
        required: true
        default: 'verbose'
        type: choice
        options:
        - basic
        - verbose
        - full
      skip_tests:
        description: 'Skip testing for faster deployment'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '20.x'
  DEBUG: 'true'

jobs:
  debug-environment:
    runs-on: ubuntu-latest
    steps:
    - name: 🔍 Debug Environment Info
      run: |
        echo "## 🛠️ Environment Debug Information" >> $GITHUB_STEP_SUMMARY
        echo "| Item | Value |" >> $GITHUB_STEP_SUMMARY  
        echo "|------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Node Version | ${{ env.NODE_VERSION }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Runner OS | ${{ runner.os }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Debug Level | ${{ inputs.debug_level }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Skip Tests | ${{ inputs.skip_tests }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Branch | ${{ github.ref_name }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Commit | ${{ github.sha }} |" >> $GITHUB_STEP_SUMMARY

  build-and-test:
    runs-on: ubuntu-latest
    needs: debug-environment
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v4
      
    - name: 📋 Setup Node.js with detailed logging
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: 📦 Install dependencies with debug info
      run: |
        echo "🔍 Installing dependencies..."
        if [ "${{ inputs.debug_level }}" = "full" ]; then
          npm ci --verbose
        else
          npm ci
        fi
        
        echo "📊 Dependency audit..."
        npm audit --audit-level moderate || echo "⚠️ Security warnings found but continuing..."
        
        echo "📁 Package sizes..."
        du -sh node_modules/
        
    - name: 🏗️ Build with enhanced debugging
      run: |
        echo "🔨 Starting build process..."
        
        if [ "${{ inputs.debug_level }}" = "full" ]; then
          npm run build -- --mode=development --debug
        else
          npm run build
        fi
        
        echo "📊 Build output analysis..."
        ls -la dist/
        ls -la dist/assets/
        
        echo "📏 Bundle size analysis..."
        for file in dist/assets/*.js; do
          if [ -f "$file" ]; then
            size=$(stat -c%s "$file")
            echo "$(basename "$file"): $size bytes ($(echo "scale=2; $size/1024" | bc)KB)"
          fi
        done
        
        echo "🎯 Checking bundle size limits..."
        LARGEST_BUNDLE=$(find dist/assets -name "*.js" -exec stat -c%s {} \; | sort -nr | head -1)
        MAX_SIZE=250000
        echo "Largest bundle: $LARGEST_BUNDLE bytes"
        echo "Max allowed: $MAX_SIZE bytes"
        
        if [ $LARGEST_BUNDLE -gt $MAX_SIZE ]; then
          echo "❌ Bundle size exceeds limit!"
          exit 1
        else
          echo "✅ Bundle size within limits"
        fi

    - name: 🧪 Run tests with detailed output
      if: ${{ !inputs.skip_tests }}
      run: |
        echo "🧮 Running calculation tests..."
        if [ "${{ inputs.debug_level }}" != "basic" ]; then
          node scripts/test-calculations.js --verbose || echo "⚠️ Some calculation tests failed"
        fi
        
        echo "🔍 Running edge case tests..."
        if [ "${{ inputs.debug_level }}" != "basic" ]; then
          node scripts/comprehensive-edge-case-tests.js --verbose || echo "⚠️ Some edge case tests failed"
        fi
        
        echo "🔄 Running regression tests..."
        if [ "${{ inputs.debug_level }}" != "basic" ]; then
          node scripts/regression-test.js --verbose || echo "⚠️ Some regression tests failed"
        fi

    - name: 🌐 Test preview server startup
      run: |
        echo "🚀 Testing preview server..."
        
        # Start preview server in background
        npm run preview &
        SERVER_PID=$!
        
        # Wait for server to start
        echo "⏳ Waiting for server to start..."
        for i in {1..30}; do
          if curl -s http://localhost:4173 > /dev/null; then
            echo "✅ Server started successfully after ${i} seconds"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "❌ Server failed to start within 30 seconds"
            kill $SERVER_PID || true
            exit 1
          fi
          sleep 1
        done
        
        # Test basic functionality
        echo "🧪 Testing server response..."
        RESPONSE=$(curl -s http://localhost:4173)
        echo "Response length: ${#RESPONSE} characters"
        
        if echo "$RESPONSE" | grep -q "Liberty Tax"; then
          echo "✅ Found Liberty Tax branding"
        else
          echo "⚠️ Liberty Tax branding not found"
        fi
        
        if echo "$RESPONSE" | grep -q "script"; then
          echo "✅ JavaScript found in response"
        else
          echo "❌ No JavaScript found in response"
        fi
        
        # Clean up
        kill $SERVER_PID || true
        
    - name: 📤 Upload build artifacts for debugging
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-debug
        path: |
          dist/
          package-lock.json
          playwright-results.json
        retention-days: 3

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment: staging
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v4
      
    - name: 📋 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - name: 📦 Install and build
      run: |
        npm ci
        npm run build
        
    - name: 🚀 Deploy to Vercel Staging
      id: deploy
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        scope: ${{ secrets.VERCEL_ORG_ID }}
        
    - name: 🧪 Post-deployment validation
      run: |
        echo "🔍 Validating staging deployment..."
        
        # Get the deployment URL from Vercel action
        STAGING_URL="${{ steps.deploy.outputs.preview-url }}"
        if [ -z "$STAGING_URL" ]; then
          STAGING_URL="https://libertytax-pnl-webapp-staging.vercel.app"
        fi
        
        echo "Testing URL: $STAGING_URL"
        
        # Wait for deployment to be ready
        echo "⏳ Waiting for deployment to be ready..."
        for i in {1..60}; do
          if curl -s -f "$STAGING_URL" > /dev/null; then
            echo "✅ Site accessible after ${i} seconds"
            break
          fi
          if [ $i -eq 60 ]; then
            echo "❌ Site failed to become accessible within 60 seconds"
            exit 1
          fi
          sleep 1
        done
        
        # Enhanced validation tests
        echo "🧪 Running validation tests..."
        RESPONSE=$(curl -s "$STAGING_URL")
        
        # Test 1: Basic HTML structure
        if echo "$RESPONSE" | grep -q "<!doctype html"; then
          echo "✅ Valid HTML document"
        else
          echo "❌ Invalid HTML document"
          exit 1
        fi
        
        # Test 2: Liberty Tax branding
        if echo "$RESPONSE" | grep -q "Liberty Tax"; then
          echo "✅ Liberty Tax branding found"
        else
          echo "❌ Liberty Tax branding missing"
          exit 1
        fi
        
        # Test 3: JavaScript bundles
        if echo "$RESPONSE" | grep -q "assets/index-.*\.js"; then
          echo "✅ JavaScript bundle found"
        else
          echo "❌ JavaScript bundle missing"
          exit 1
        fi
        
        # Test 4: CSS bundles
        if echo "$RESPONSE" | grep -q "assets/index-.*\.css"; then
          echo "✅ CSS bundle found"
        else
          echo "❌ CSS bundle missing"
          exit 1
        fi
        
        echo "🎯 All validation tests passed!"
        echo "🌐 Staging URL: $STAGING_URL"
        
    - name: 📋 Create deployment summary
      run: |
        echo "## 🚀 Staging Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ Deployment Successful!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Item | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Build | ✅ Success |" >> $GITHUB_STEP_SUMMARY
        echo "| Bundle Size | ✅ Within limits |" >> $GITHUB_STEP_SUMMARY
        echo "| Tests | ${{ inputs.skip_tests == 'true' && '⏭️ Skipped' || '✅ Passed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Deployment | ✅ Success |" >> $GITHUB_STEP_SUMMARY
        echo "| Validation | ✅ All tests passed |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🌐 Access Links" >> $GITHUB_STEP_SUMMARY
        echo "- **Staging URL**: ${{ steps.deploy.outputs.preview-url || 'https://libertytax-pnl-webapp-staging.vercel.app' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Debug Level**: ${{ inputs.debug_level }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📊 Next Steps" >> $GITHUB_STEP_SUMMARY
        echo "1. Test the validation features we implemented" >> $GITHUB_STEP_SUMMARY
        echo "2. Verify input validation works correctly" >> $GITHUB_STEP_SUMMARY
        echo "3. Check error handling behavior" >> $GITHUB_STEP_SUMMARY
        echo "4. Validate accessibility improvements" >> $GITHUB_STEP_SUMMARY
