name: E2E Matrix

on:
  push:
    branches: [main, develop, Dev_09202025, 'feat/**', 'fix/**']
  pull_request:
    branches: [main, develop, Dev_09202025]

jobs:
  e2e:
    name: Playwright E2E (${{ matrix.target }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: react
            baseURL: http://localhost:3000
          - target: angular
            baseURL: http://localhost:4200
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install root dependencies
        run: npm ci

      - name: Install Angular dependencies (if present)
        run: |
          if [ -f "angular/package.json" ]; then
            cd angular && npm ci
          else
            echo "No angular/package.json; skipping Angular deps"
          fi

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Start target server
        run: |
          if [ "${{ matrix.target }}" = "react" ]; then
            npm run dev:react &
            npx wait-on --timeout 180000 ${{ matrix.baseURL }}
          else
            cd angular && npx ng serve --port 4200 --configuration=development &
            npx wait-on --timeout 180000 http-get://localhost:4200
          fi

      - name: Run Playwright tests
        env:
          PW_BASEURL: ${{ matrix.baseURL }}
          # Enable verbose diagnostics from Playwright
          DEBUG: pw:api
        run: |
          if [ "${{ matrix.target }}" = "react" ]; then
            if ls test/e2e/*.* 1> /dev/null 2>&1; then
              npx playwright test -c playwright.config.ts || echo "React E2E failed (non-blocking)"
            else
              echo "No React Playwright tests found, skipping"
            fi
          else
            if ls test/e2e/*.* 1> /dev/null 2>&1; then
              npx playwright test -c playwright.config.js || echo "Angular E2E failed (non-blocking)"
            else
              echo "No Angular Playwright tests found, skipping"
            fi
          fi

      - name: Cleanup background servers
        if: always()
        run: |
          pkill -f "ng serve" || true
          pkill -f "vite" || true

      - name: Upload Playwright report (on failure)
        if: failure() || (success() && matrix.target == 'react')
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.target }}
          path: playwright-report/

      - name: Upload test results and traces (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts-${{ matrix.target }}
          path: |
            test-results/**
            playwright-report/**
            **/test-results/**
            **/playwright-report/**
